# command `brew bundle`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
#upgrade

install autojump
install git
install tig
install tree
install wget
install terminal-notifier

tap homebrew/dupes
install homebrew/dupes/openssh

install node
install ruby

tap homebrew/dupes
tap homebrew/versions
tap josegonzalez/homebrew-php
install josegonzalez/php/php55 --with-fpm --with-pgsql --without-apache
install josegonzalez/php/php55-intl
install josegonzalez/php/php55-mcrypt
install josegonzalez/php/php55-memcache
install josegonzalez/php/php55-memcached
install josegonzalez/php/php55-xdebug
unlink php55
link php55
install composer

install memcached
install mysql
install nginx
install postgis
install postgresql
install sqlite

tap phinze/homebrew-cask
install phinze/cask/brew-cask

# Install Applications
cask install alfred
cask install appcleaner
cask install caffeine
cask install dash
cask install dropbox
cask install google-chrome
cask install google-japanese-ime
cask install launchrocket
cask install skype
cask install sourcetree
cask install totalterminal
cask install vagrant
cask install virtualbox

# Alfred Setting
cask alfred link

# Remove outdated versions from the cellar
cleanup
